### ISSUE TITLE
is there a way to support multi start processes?

### ISSUE THREAD

**Issue by ezteki** [paketo-buildpacks/python-start#139]
## What happened?
```shell
# Procfile
web1: uwsgi --ini /workspace/uwsgi.ini
beat: celery -A ifcloud beat -l info
worker: celery -A ifcloud worker -l INFO
web: gunicorn ifcloud.wsgi:application
```

sometime multi start processes is necessary，but it seems that this repo DO NOT support ?

is there a plan or not ?

**Comment by robdimsdale** [comment]
@pyfs I think the Procfile should support multiple processes. What is the error that you are seeing? Can you post some output, and describing what happens when you try to run with the above Procfile?

As a side note, using a Procfile overrides the start command provided by this buildpack, so this question might better be suited to https://github.com/paketo-buildpacks/python. We can leave it here for now, though.

@paketo-buildpacks/utilities-maintainers can you confirm that the [Procfile buildpack](https://github.com/paketo-buildpacks/procfile) supports multiple processes, and what the syntax for that is? I can't easily determine this from the README on that repo.

**Comment by robdimsdale** [comment]
While we wait for an authoritative answer from the Utilities maintainers, I wanted to clarify your expected use-case @pyfs .

Do you expect that a `docker run <my-image>` with the above `Procfile` would start all of the processes simultaneously / in paralell? If so, that isn't supported. Having multiple processes in the `Procfile` allows you to `docker run <my-image> <some-process>` where `<some-process>` is one of the defined processes in the `Procfile`.

**Comment by ForestEckhardt** [comment]
As far as I can tell from [this line](https://github.com/paketo-buildpacks/procfile/blob/bc5a4da26b84cc4c37a2c623bf41c98d5fb0d47f/procfile/build.go#L62) you should be able to define multiple process types in the Procfile and they will all be picked up and as far as I can tell from [this example](https://devcenter.heroku.com/articles/procfile#more-process-type-examples) multiple process type in one Procfile is supported by the file format.

**Comment by joshuatcasey** [comment]
> define multiple process types in the Procfile and they will all be picked up

@ForestEckhardt could you clarify what it means for a process to be picked up? I understand any number of processes can be defined in the launch image, but would you expect more than one to be run?

It looks like the [buildpack spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#launch) and [platform spec](https://github.com/buildpacks/spec/blob/main/platform.md#launcher) anticipate selecting exactly one process.

**Comment by ForestEckhardt** [comment]
As far as I am aware it will only run 1 process at any time. All of the processes will be available to run on the final image but one will need to be selected (either the default process or one selected by the user).

**Comment by robdimsdale** [comment]
@ezteki does the above answer make sense to you? Currently buildpacks do not have a built-in mechanism for managing multiple processes in parallel - you would have to do that yourself via a procfile and some additional process manager.

I'm going to close this issue as I think we have an answer to the original question. Feel free to re-open if you have additional questions or if we can clarify anything.
