### ISSUE TITLE
Pip-installable app fails detection when in module

### ISSUE THREAD

**Issue by mterrel** [paketo-buildpacks/python-start#196]
## Expected Behavior

When trying to build a Python app that has a `requirements.txt`, the buildpack group for Pip installation should pass detection and build the app image.

## Current Behavior

The app image does not build and instead gives the following error:

```
ERROR: No buildpack groups passed detection.
```

The reason that Pip installs work in other cases is because there are often `.py` files in the repo root directory. However, if the main app is a local Python module (i.e. in a directory), and there are no other `.py` files in the root, the `python-start` buildpack fails detection even though the `pip-install` buildpack passed detection and this is a valid Python app.

Other Python package managers are correctly supported by `python-start`, even in the case where the main app is in a local Python module because `python-start` detects the package manager's files, such as `pyproject.toml`.

## Workaround

Add an empty file with a `.py` extension to the root of the repo.

## Possible Solution

Check for `requirements.txt` in the detect phase of `python-start`, similarly to how it already checks for `pyproject.toml` or `package-list.txt`.

## Steps to Reproduce

This repro is based on the [official tutorial](https://github.com/pallets/flask/tree/main/examples/tutorial) from the Flask project, upon which **many** Python projects are based. However, it substitutes Pip and `requirements.txt` (which are supported by Paketo) instead of `setup.py` (which is unsupported by Paketo).

1. `git clone https://github.com/mterrel/flask-tutorial`
2. `cd flask-tutorial`
3. `pack build  flask-tutorial --buildpack paketo-buildpacks/python --builder paketobuildpacks/builder:base`

Step 3 output:

```
flask-tutorial$ pack build  flask-tutorial --buildpack paketo-buildpacks/python --builder paketobuildpacks/builder:base
base: Pulling from paketobuildpacks/builder
Digest: sha256:cd5c630c64e82fc5bf2af3f4fb6f2a5be25f232e9abca68c3103280b7a265c44
Status: Image is up to date for paketobuildpacks/builder:base
base-cnb: Pulling from paketobuildpacks/run
Digest: sha256:94dcde503f31bfe2df0a06fe77c13af2adde688322f4c5e39142878b35b5ad66
Status: Image is up to date for paketobuildpacks/run:base-cnb
Previous image with name "flask-tutorial" not found
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

When run with `-v`, I believe the important part of the output is this:

```
======== Output: paketo-buildpacks/python-start@0.12.2 ========
No *.py, environment.yml, pyproject.toml, or package-list.txt found
======== Results ========
pass: paketo-buildpacks/ca-certificates@3.4.0
pass: paketo-buildpacks/watchexec@2.6.0
pass: paketo-buildpacks/cpython@1.4.0
pass: paketo-buildpacks/pip@0.15.0
pass: paketo-buildpacks/pip-install@0.5.2     <==== pip-install passes
fail: paketo-buildpacks/python-start@0.12.2   <==== python-start fails
pass: paketo-buildpacks/procfile@5.4.0
skip: paketo-buildpacks/environment-variables@4.3.0
skip: paketo-buildpacks/image-labels@4.3.0
```

## Motivations

We recently added Python support for [Adaptable.io](https://adaptable.io) via Paketo buildpacks. However, some users that have this type of app structure are seeing that their apps do not build an image due to this issue.

**Comment by robdimsdale** [comment]
@mterrel thanks for raising this. I agree that we should be able to support this use case.

Honestly, it looks like an oversight on our part.

If you want to submit a PR for this, it would be gladly accepted. It would look something like the following:

1. Add a check for this file, similar to [this](https://github.com/paketo-buildpacks/python-start/blob/0a268492dc008a532e5b238c0fb50742517ad923/detect.go#L40-L43):
    ```
    lockFile, err := fs.Exists(filepath.Join(context.WorkingDir, "package-list.txt"))
    if err != nil {
        return packit.DetectResult{}, packit.Fail.WithMessage("failed trying to stat package-list.txt: %w", err)
    }
    ```
1. Add the new file to the [list of required files](https://github.com/paketo-buildpacks/python-start/blob/0a268492dc008a532e5b238c0fb50742517ad923/detect.go#L55-L57):
    ```
    if !envFile && !lockFile && !pyprojectTOMLFile && len(pythonFiles) < 1 {
        return packit.DetectResult{}, packit.Fail.WithMessage("No *.py, environment.yml, pyproject.toml, or package-list.txt found")
    }
    ```

As with all features, we'd want to test it. I would add a unit test similar to the [`package-list.txt` test case](https://github.com/paketo-buildpacks/python-start/blob/0a268492dc008a532e5b238c0fb50742517ad923/detect_test.go#L228-L240).

Additionally, I would also add an integration test - creating a new fixtures from the flask example you linked above would be great, and we would add a new test case similar to [`site-packages`](https://github.com/paketo-buildpacks/python-start/blob/0a268492dc008a532e5b238c0fb50742517ad923/integration/default_test.go#L88-L126).

If you don't have the bandwidth to get to this, no problem. We will add it to our roadmap and get to it at some point.

**Comment by mterrel** [comment]
@robdimsdale Thanks for taking a look at this. It definitely looked like a simple oversight to me as well. Although once I dug into how the group detection worked, I was a little surprised to see that `python-start` essentially has to duplicate the detection logic of every supported package manager.

I'm open to submitting a PR, but I couldn't easily and quickly figure out how to do manual and integration testing of my changes. Are there any docs on how all that works?

I'm not quite sure how quickly I can get to the PR though, so if you could also add it to your roadmap, that would be great.

**Comment by robdimsdale** [comment]
Yeah, it is an unfortunate aspect of the way the upstream [buildpack detection spec](https://github.com/buildpacks/spec/blob/main/buildpack.md) is defined - buildpacks can't communicate with either other during the Detect phase to conditionally detect based on other buildpacks' detection results.

So we either duplicate the logic, or we set this buildpack to always participate. I don't think either option is ideal, but we have to pick one!

I think the integration tests are the best way to drive out new behavior. To facilitate running the tests, we provide helper scripts. They are [documented in the README](https://github.com/paketo-buildpacks/python-start#run-tests). If you think there are improvements to be made, we would love to hear your thoughts here, too.

If you do want to test your changes to this buildpack manually, you would have to package it and build it ([steps in README](https://github.com/paketo-buildpacks/python-start#usage) and then run a pack build with a command that looks something like:

```
pack build \
  --builder paketobuildpacks/builder:base \
  --buildpack paketo-buildpacks/cpython \
  --buildpack paketo-buildpacks/pip \
  --buildpack paketo-buildpacks/pip-install \
  --buildpack /path/to/local/python-start/buildpack.tgz \
  my-app
```

Typically if you use the provided packaging scripts, the local copy of the buildpack will be under the `build/` directory of this repository.

This command is a little convoluted because you have to create a new build order with all the required buildpacks. There is nothing in the spec to support swapping out individual buildpacks from a build order (e.g. from `python-buildpacks/python`).
